### PR TITLE
Bump the branch and runtime to 22.08

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by hfiguiere** [comment]
the branch needs to be created

**Comment by Erick555** [comment]
I recommend apps to use llvm14. If there is app that doesn't work with 14 then we can consider re-release of 13 for 22.08 but it would be best to let it die in peace.

**Comment by farribeiro** [comment]
Thunderbird app use llvm13

**Comment by Erick555** [comment]
I know and I move it to llvm14 when I will be updating runtime.

**Comment by orowith2os** [comment]
Could this be added? I'd appreciate having it, though there's no real reason for it aside from testing, since I think llvm14 would work well enough anyways...

**Comment by Erick555** [comment]
Well as you said yourself there is no real reason and it's EOL from upstream long time ago.

**Pull request closed without merging**
